export const uiText = {
  app: {
    brand: 'Sample platform',
    title: 'Items',
    subtitle: 'A simple workspace for the things worth keeping track of.',
  },
  form: {
    newEyebrow: 'New item',
    editEyebrow: 'Editing item',
    createTitle: 'Add something useful',
    editTitle: 'Update item details',
    nameLabel: 'Name',
    namePlaceholder: 'e.g. Standing desk',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Add a short description (optional)',
    nameRequired: 'Please enter an item name.',
    create: 'Create item',
    update: 'Save changes',
    saving: 'Saving…',
    cancel: 'Cancel',
  },
  list: {
    eyebrow: 'Your collection',
    title: 'Items',
    singular: 'item',
    plural: 'items',
    refresh: 'Refresh',
    refreshing: 'Refreshing…',
    emptyTitle: 'No items yet',
    emptyDescription: 'Create your first item using the form.',
    loading: 'Loading items…',
    loadErrorTitle: 'We couldn’t load your items',
    retry: 'Try again',
    dismiss: 'Dismiss',
    noDescription: 'No description provided.',
    edit: 'Edit',
    delete: 'Delete',
    deleting: 'Deleting…',
    deleteConfirmation: 'Delete this item? This action cannot be undone.',
    updated: 'Updated',
  },
} as const
